// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://elwmhfehsryakmpslupn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVsd21oZmVoc3J5YWttcHNsdXBuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwNDM1MjcsImV4cCI6MjA2MjYxOTUyN30.BjCBapXE32BM96Wmc9ECWQut4qWgYsnXRamlnOulj-Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);